language: node_js
node_js:
  - 14.6
cache: yarn
install:
  - yarn install
script:
  - echo "skipping tests"
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  on:
    branch: main
